# Generated by Django 6.0.5 on 2026-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='activity_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='billing_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
