# Generated by Django 6.0.5 on 2026-05-25 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_by', models.CharField(default='anonymous_analyst', max_length=255)),
                ('old_value', models.JSONField(help_text='Stores the serialized state before changes')),
                ('new_value', models.JSONField(help_text='Stores the serialized state after changes')),
                ('change_reason', models.TextField(help_text='Justification for the change')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
