# Generated by Django 6.0.5 on 2026-05-25 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel/Procurement Export'), ('UTILITY', 'Utility Electricity Export'), ('TRAVEL', 'Corporate Travel Export')], max_length=50)),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_by', models.CharField(default='system_user', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing File'), ('SUCCESS', 'Ingested Successfully'), ('FAILED', 'Ingestion Failed')], default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization')),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_json', models.JSONField(help_text='Stores the exact raw row columns parsed from CSV')),
                ('processing_status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('SUCCESS', 'Successfully Normalized'), ('SUSPICIOUS', 'Normalized with Suspicious Flags'), ('FAILED', 'Normalization Failed')], default='UNPROCESSED', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.datasource')),
            ],
            options={
                'db_table': 'raw_records',
            },
        ),
    ]
